# Generated by Django 3.2.25 on 2024-05-14 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_remove_settings_ischecked'),
    ]

    operations = [
        migrations.RenameField(
            model_name='settings',
            old_name='repository_url',
            new_name='repository_name',
        ),
    ]
