# Generated by Django 3.2.25 on 2024-05-20 04:04

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_alter_comment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='related_documents',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
        ),
    ]
