# Generated by Django 3.2.25 on 2024-05-24 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_alter_article_related_documents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='related_documents',
        ),
    ]
