# Generated by Django 3.2.15 on 2022-11-28 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('explanation', '0002_auto_20221128_1655'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Explanation',
        ),
    ]
