# Generated by Django 3.2.15 on 2022-12-06 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explanation', '0003_rename_post_explanation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='explanation',
            name='text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='explanation',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
