# Generated by Django 3.2.15 on 2022-12-08 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('explanation', '0005_alter_explanation_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='explanation',
            name='date',
        ),
    ]
