# Generated by Django 3.2.15 on 2023-04-03 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explanation', '0006_remove_explanation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='explanation',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
