# Generated by Django 3.2.15 on 2023-04-06 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explanation', '0008_auto_20230404_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='explanation',
            name='title',
            field=models.CharField(default='test', max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
