# Generated by Django 3.2.15 on 2023-04-06 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explanation', '0009_alter_explanation_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='explanation',
            name='text',
            field=models.TextField(default='example'),
            preserve_default=False,
        ),
    ]
