from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Generated by Django 4.0.1 on 2023-09-14 11:11
    """

    dependencies = [
        ('explanation', '0010_alter_explanation_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='explanation',
            name='text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='explanation',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
