# Generated by Django 3.2.15 on 2023-04-06 06:52

from django.db import migrations, models
import explanation.models


class Migration(migrations.Migration):

    dependencies = [
        ('explanation', '0010_alter_explanation_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='explanation',
            name='text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='explanation',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
